<?php
globalvar_add_locale(array (
	'User' => '',
	'List of %s' => '',
	'You can use this page to manage Profile-Type in the Section. ' => '',
	'The Profile of Users can be extent using Profile-Type. ' => '',
	'This Profile extention is flexible and suitable for database of human resources.' => '',
	'Add a new Profile-Type' => '',
	'type name' => '',
	'description' => '',
	'allowed group' => '',
));
?>