<?php
globalvar_add_locale(array (
	'Manage Theme' => '',
	'The selected theme has been successfully initialized.' => '',
	'Your theme has been successfully reset.' => '',
	'Your custom theme directories have been successfully cleared.' => '',
	'Theme custom image' => '',
	'Theme' => '',
	'Custom CSS' => '',
	'Your CSS file has been successfully saved.' => '',
	'The selected theme can not be configured.' => '',
	'Your custom theme directory does not exist. The directory has been created.' => '',
	'The given primary widget position does not exist.' => '',
	'Edit Custom CSS : ' => '',
	'You can select and edit CSS file from the followed list to customize your theme.' => '',
	'You can select theme of Section with this page. Afterwards, you can customize your theme by :' => '',
	'Or you can <a href="%s"><strong>reset your theme</strong></a>.' => '',
	'For theme development, you should <a href="%s"><strong>clear custom theme directories</strong></a> to simplify your work.' => '',
	'current theme' => '',
	'use this theme' => '',
));
?>