<?php
globalvar_add_locale(array (
	'new password' => '',
	'confirm password' => '',
	'Forget Password' => '',
	'Enter your email, which you use for your account. ' => '',
	'We will send you a link to this email. ' => '',
	'You can use this link to reset your password.' => '',
	'The given email : %s does not exist.' => '',
	'Your given code from the image was wrong. Data is not inserted.' => '',
	'Reset your password.' => '',
	'You can use the following link to reset your password : ' => '',
	'Reset Password' => '',
	'Your password has been already changed, please login.' => '',
	'Password is too short.' => '',
	'Password strength is very strong.' => '',
	'Password strength is strong.' => '',
	'Password strength is medium.' => '',
	'Password strength is weak.' => '',
	'Password is mismathed.' => '',
	'The requested URI for password resetting is invalid.' => '',
	'email' => '',
));
?>