<?php
globalvar_add_locale(array (
	'Activity Configuration' => '',
	'Activity' => '',
	'icon size' => '',
	'show avatar' => '',
	'show category icon' => '',
	'show avatar for comments' => '',
	'user signature' => '',
	'show in rendered activity' => '',
	'Activity Calendar' => '',
	'Write new Activity entry' => '',
	'Calendar of Activities in this the Section.' => '',
	'Last posted Activities' => '',
	'Last commented Activities' => '',
	'Activity has been successfully deactivated' => '',
	'from' => '',
	'to' => '',
	'List of Activies' => '',
	'icon' => '',
	'activity start date' => '',
	'activity end date' => '',
));
?>