<?php
globalvar_add_locale(array (
	'Manage Module' => '',
	'Module configuration has been successfully saved.' => '',
	'Module has been successfully activated.' => '',
	'Module has been successfully deactivated.' => '',
	'Module has been successfully refreshed.' => '',
	'Check this field and submit. Checked modules will be activated.' => '',
	'deactivate module' => '',
	'activate module' => '',
	'refresh module' => '',
	'module name / description' => '',
	'enable' => '',
	'activate' => '',
	'refresh' => '',
	'Private Module' => '',
	'The followed modules can be used only in this Section.' => '',
	'Public Module' => '',
	'submit Module configuration' => '',
));
?>