<?php
globalvar_add_locale(array (
	'Configure Account' => '',
	'Your account configuration has been successfully updated.' => '',
	'Account Configuration : %s' => '',
	'signature' => '',
	'default language for my user interface' => '',
	'send me an email by' => '',
	'who can see my profile' => '',
	'who can send me an email' => '',
	'Everybody included anonymous visitor' => '',
	'All authenticated users' => '',
	'Only you and administration' => '',
	'someone comments on my contributions' => '',
));
?>