<?php
globalvar_add_locale(array (
	'promote' => '',
	'Blog Configuration' => '',
	'Blog' => '',
	'icon' => '',
	'introduction' => '',
	'icon size' => '',
	'show avatar' => '',
	'show category icon' => '',
	'show avatar for comments' => '',
	'user signature' => '',
	'next/previous entry' => '',
	'show in rendered blog' => '',
	'blog entries per page' => '',
	'Blogging system for Ximple (see <a href="http://en.wikipedia.org/wiki/Blog">Wikipedia</a> for more information about blog).' => '',
	'Last posted Blogs' => '',
	'Last commented Blogs' => '',
	'Promoted Blogs' => '',
	'Blog has been successfully deactivated' => '',
	'Write new Blog entry' => '',
));
?>