<?php
globalvar_add_locale(array (
	'promote' => 'โปรโมท',
	'Blog Configuration' => 'ปรับแต่งค่าสำหรับ Blog',
	'Blog' => 'Blog',
	'icon' => 'ไอคอน',
	'introduction' => 'บทนำ',
	'icon size' => 'ขนาดไอคอน',
	'show avatar' => 'แสดงผลอวตาล',
	'show category icon' => 'แสดงผลไอคอนหมวดหมู่',
	'show avatar for comments' => 'แสดงผลอวตาลสำหรับความคิดเห็น',
	'user signature' => 'ลายเซ็นผู้ใช้',
	'next/previous entry' => 'blog ก่อนหน้า/หลังจาก blog ที่อ่าน',
	'show in rendered blog' => 'แสดงผล',
	'blog entries per page' => 'จำนวน blog ต่อหน้า',
	'Blogging system for Ximple (see <a href="http://en.wikipedia.org/wiki/Blog">Wikipedia</a> for more information about blog).' => 'ระบบ Blog สำหรับ Ximple (อ่าน <a href="http://en.wikipedia.org/wiki/Blog">Wikipedia</a> สำหรับข้อมูลเพิ่มเติม).',
	'Last posted Blogs' => 'Blog ล่าสุด',
	'Last commented Blogs' => 'Blog ที่มีความคิดเห็นล่าสุด',
	'Promoted Blogs' => 'Blog ที่ได้รับการโปรโมท',
	'Write new Blog entry' => 'เขียน Blog ใหม่',
));
?>
