<?php
globalvar_add_locale(array (
	'*' => '',
	'**' => '',
	'***' => '',
	'****' => '',
	'*****' => '',
	'star' => '',
	'description' => '',
	'reviewee' => '',
	'Review' => '',
	'Comment writing and reading with rating and opinion point.' => '',
	'Review has been successfully activated' => '',
	'Review has been successfully deactivated' => '',
	'Review by : ' => '',
	'Review for reviewee: ' => '',
	'List of all Review' => '',
	'List of %s' => '',
	'Add new Review' => '',
	'This review already has been rated by this reviewer' => '',
	'Please choose reviewee before review.' => '',
	'Submit new Review for %s' => '',
));
?>