<?php
globalvar_add_locale(array (
	'comment permission' => '',
	'status' => '',
	'icon' => '',
	'author name' => '',
	'If blank, your login-name will be shown.' => '',
	'introduction' => '',
	'Page' => '',
	'Directory' => '',
	'You are not allowed to view the selected Page.' => '',
	'Pages tagged by %s' => '',
	'list of pages' => '',
	'index page' => '',
	'written by' => '',
	'edited by' => '',
	'discription and icon of pages' => '',
));
?>