<?php
globalvar_add_locale(array (
	'icon size' => '',
	'player width' => '',
	'player height' => '',
	'number of shown video entries per page' => '',
	'maximum file size : %s' => '',
	'support only .flv file.' => '',
	'icon' => '',
	'video file' => '',
	'size' => '',
	'Video' => '',
	'Video support only .flv file.' => '',
	'With Video Module, you can provide video streaming on your website. ' => '',
	'Be careful with the bandwidth. Vedio streaming is very bandwidth hungry.' => '',
	'Last posted Videos' => '',
	'Last commented Videos' => '',
	'Video has been successfully deactivated' => '',
	'Video Configuration' => '',
	'download' => '',
	'embed' => '',
));
?>