<?php
globalvar_add_locale(array (
	'section name' => '',
	'Section name must be longer than 4 characters and unique' => '',
	'section URI' => '',
	'For example : http://mydomain.com/. The last character must be /.' => '',
	'section path' => '',
	'Section path must be longer than 4 characters, unique and consists of a-z, A-Z, 0-9, _, -. ' => '',
	'Section is an instance of Ximple. ' => '',
	'You can install Ximple only one time on a server and create multiple Sections. ' => '',
	'Every Section is a self-contained website and has the own configurations but joint user and database.' => '',
	'This can dramatically reduce your work for maintenance of multiple websites.' => '',
	'List of %s' => '',
	'Section is not allowed to be deleted.' => '',
	'Section name is too short.' => '',
	'Section path is too short.' => '',
	'Section name exists.' => '',
	'Section path exists.' => '',
	'Section path is not conformed.' => '',
	'Given URI is not conformed.' => '',
	'Section can not be created. Please check permission of %s.' => '',
));
?>