<?php
globalvar_add_locale(array (
	'everyone can vote' => '',
	'only authenticated user can vote' => '',
	'only user with Poll-Voter roll can vote' => '',
	'comment label' => '',
	'comments number per page' => '',
	'choise' => '',
	'topic' => '',
	'description' => '',
	'choises' => '',
	'end date' => '',
	'vote permission' => '',
	'comment permission' => '',
	'Poll module for XimpleCMS. It can be use as a widget or can be embed in other module.' => '',
	'Poll' => '',
	'Please, write your opinion.' => '',
	'see more' => '',
	'List of Polls' => '',
	'Add or edit poll for this entry' => '',
	'permission' => '',
	'Poll Configuration' => '',
));
?>