<?php
globalvar_add_locale(array (
	'Menu' => '',
	'Add a new Menu' => '',
	'Edit Menu' => '',
	'Menus sort setting has been updated.' => '',
	'menu title' => '',
	'URI' => '',
	'Absolute URI e.g. http://www.wikipedia.org or Ximple internal URI e.g. blog/111.' => '',
	'includes Widget' => '',
	'Use <a href="%s">widget interface</a> for Widget configuration.' => '',
	'Menu Edit' => '',
	'Legend' => '',
	'Sort by drag-and-drop' => '',
	'Edit and Configure Menu' => '',
	'Delete Menu' => '',
	'You can use this form to sort Menus by drag-and-drop. Please, do not forget to click submit.' => '',
	'Add new Menu' => '',
	'save Menus' => '',
));
?>