<?php
globalvar_add_locale(array (
	'Guestbook' => '',
	'Sign on %s' => '',
	'Let your visitors sign and write something on your web site.' => '',
	'Guestbook has been successfully activated' => '',
	'You can now assess Guestbook with <a href="%s">this link</a>. Add this link somewhere to Widget or Menu.' => '',
	'Guestbook has been successfully deactivated' => '',
	'Please sign on our website.' => '',
	'your name' => 'ชื่อของคุณ',
	'your email (not show)' => '',
	'your opinion' => '',
));
?>
