<h1>Structure of External Document</h1>
<p>ที่&nbsp&nbsp:&nbsp&nbsp<?=$at?></p>
<p>ส่วนราชการเจ้าของเรื่อง&nbsp&nbsp:&nbsp&nbsp<?=$government_owner?></p>
<p>ที่ตั้งและรหัสไปรษณีย์&nbsp&nbsp:&nbsp&nbsp<?=$address?></p>
<p>เดือน&nbsp&nbsp:&nbsp&nbsp<?=$month?></p>
<p>ปี&nbsp&nbsp:&nbsp&nbsp<?=$year?></p>
<p>เรื่อง&nbsp&nbsp:&nbsp&nbsp<?=$subject?></p>
<p>คำขึ้นต้น&nbsp&nbsp:&nbsp&nbsp<?=$introduction?></p>
<p><?=$introduction?>&nbsp&nbsp:&nbsp&nbsp<?=$introduction_detail?></p>
<p>อ้างถึง&nbsp&nbsp:&nbsp&nbsp<?=$refer?></p>
<p>สิ่งที่ส่งมาด้วย&nbsp&nbsp:&nbsp&nbsp<?=$enclose?></p>
<p>ข้อความ&nbsp&nbsp:&nbsp&nbsp<?=$detail?></p>
<p>คำลงท้าย&nbsp&nbsp:&nbsp&nbsp<?=$postscript?></p>
<p>ยศ&nbsp&nbsp:&nbsp&nbsp<?=$rank?></p>
<p>ชื่อ&nbsp&nbsp:&nbsp&nbsp<?=$name?></p>
<p>สกุล&nbsp&nbsp:&nbsp&nbsp<?=$surname?></p>
<p>ตำแหน่ง&nbsp&nbsp:&nbsp&nbsp<?=$position?></p>
<p>ส่วนราชการ&nbsp&nbsp:&nbsp&nbsp<?=$government_fraction?></p>
<p>โทรศัพท์&nbsp&nbsp:&nbsp&nbsp<?=$tel?></p>
<p>โทรสาร&nbsp&nbsp:&nbsp&nbsp<?=$fax?></p>
