<?php
globalvar_add_locale(array (
	'name' => '',
	'icon' => '',
	'upload file' => '',
	'size' => '',
	'description' => '',
	'allowed group' => '',
	'Check guest to allow everybody.' => '',
	'Download' => '',
	'Upload new file' => '',
	'You are not allowed to donwload this file.' => '',
	'List of %s' => '',
	'Upload new File' => '',
	'%s times downloaded' => '',
	'With Download-Module, you can provide files for downloading on your website. ' => '',
	'The files are categorized with the configurations for access permission.' => '',
	'Download has been successfully activated' => '',
	'Download has been successfully deactivated' => '',
));
?>