<?php
globalvar_add_locale(array (
	'Advertise' => '',
	'List of %s' => '',
	'Add new Advertise' => '',
	'address' => '',
	'banner' => '',
	'position' => '',
	'advertising desciption' => '',
	'customer description' => '',
	'Module for Advertising and Customer management.' => '',
	'Advertise Primaty Position' => '',
	'Advertise Configuration' => '',
	'All Advertise banners have been disabled. ' => '',
	'Position of Advertise banners must be rearranged.' => '',
	'clicks' => '',
	'Advertise Position' => '',
));
?>