<?php
globalvar_add_locale(array (
	'The registration function is turned off. You are not allowed to registry.' => '',
	'Register confirmation' => '',
	'Confirm URL' => '',
	'Click here to confirm' => '',
	'Alternative Link' => '',
	'Your registration has been successfully submitted. Please check your email to confirm the registration.' => '',
	'System error occurred. Sorry for the inconvenience. ' => '',
	'Your registration can not be proceeded. Please contact the administrator of the web-site.' => '',
	'Registration' => '',
	'Registration Configuration' => '',
	'registration enable' => '',
	'text in registration page' => '',
	'auto reply text' => '',
	'Congratulation and welcome to %s. Your registration is completed.' => '',
));
?>