<?php
globalvar_add_locale(array (
	'Comment' => '',
	'My Comments' => '',
	'Comments on my Contributions' => '',
	'Comments in %s' => '',
	'List of %s' => '',
	'guest' => '',
	'%s commented on your contribution : <a href="%s">%s</a>.' => '',
	'everybody can comment' => '',
	'only authenticated user can comment' => '',
	'read only' => '',
	'disable' => '',
	'new comment' => '',
	'commented in' => '',
	'Your name' => '',
	'Your email (will not be shown)' => '',
	'Your blog/website/homepage (optional)' => '',
	'commented by' => '',
	'Your opinion' => '',
	'comment time' => '',
));
?>