<?php
globalvar_add_locale(array (
	'page name' => '',
	'e.g. blog/111, gallery/456/Party.html' => '',
	'original URI' => '',
	'e.g. Vacation-in-New-York.html, Party.html' => '',
	'mapped URI' => '',
	'Customize URI of each page to improve SEO (Search Engine Optimization).' => '',
	'Custom URI can only be enabled by enabling "friendly URI".' => '',
	'CustomURI' => '',
	'Custom URI cannot be enabled without enabling "friendly URI".' => '',
	'The choosen mapped URI exists. Please select other URI.' => '',
	'The choosen mapped URI is too short.' => '',
	'The given mapped URI exists.' => '',
));
?>